### ISSUE TITLE
License information not updated.

### ISSUE THREAD

**Issue by cjayashantha** [josdejong/typed-function#167]
Could you please update the license information in the library. License : none raise sonar violation. yes, we can do a waiver in our side. but this would help others as well. 

Thanks in advance.

**Comment by josdejong** [comment]
What should be updated in the license file? The year?

See https://github.com/josdejong/typed-function/blob/develop/LICENSE

**Comment by josdejong** [comment]
Without more specific information I'm not sure how to help here. I've updated the year in the license. Will close this issue now, please reopen if needed.

**Comment by SLESTM** [comment]
Hello
Just a comment :  I have also seen a warning with a license detection tool in older version and it is solved now.  
Many audit tool check the license information in the package.json, and generate warning when it is not found.
The issue was not the date, but the missing information in package.json.  It has been fixed in 4.1.1 by the fix https://github.com/josdejong/typed-function/issues/168

The date in the license file was not the problem, but it is good to have updated copyright date.  😄 

Thanks a lot  @josdejong

**Comment by josdejong** [comment]
Thanks for letting me know 👍
